### ISSUE TITLE
Image doesn't get displayed correctly

### ISSUE THREAD

**Issue by xAfterLife** [morsisko/NosSplash#2]
I've been toying arround with your tool since i wasn't abled to get the Image replaced with Resource Hacker in a working manner..

I tried various things such as importing my own images, import them with set format etc. and it looked like the Height and Width are swapped for me.

I tried the same thing with extracting the Official Splash files and re-importing them to see if the issue still persists with the files that are already embedded in the File and the same thing happens again.

![image](https://user-images.githubusercontent.com/23660594/131374408-c3d0209b-466e-434b-972b-5c9e9077f7c5.png)

_*Black bar is mine, white field is from the Splash Screen_

**Comment by morsisko** [comment]
Thanks for report, not sure if they changed something in recent updates or what. It should work now. If you installed the package via pip you can upload it now using `python -m pip install nosplash --upgrade`
